# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"

# This page should be the root of your website. It's important.
page = "https://www.notion.so/lulopdz/Personal-Home-116e155f8e5d4a0ca829f868139bf9f1?pvs=4"
